import type { Advice, PlayerState, TableState } from '../types';

export const players: PlayerState[] = [
  {
    id: 'hero',
    name: 'Ryanchl',
    seat: 1,
    position: 'BTN',
    stack: 9900,
    stack_bb: 99,
    street_bet: 100,
    total_contribution: 100,
    last_action: null,
    status: 'active',
    is_dealer: true,
    is_small_blind: false,
    is_big_blind: false,
    profile: {
      initial: 'unknown',
      estimated: 'joueur principal',
      confidence: 1,
      hands_observed: 0,
      adaptation_enabled: false,
    },
  },
  {
    id: 'player-2',
    name: 'Camille',
    seat: 2,
    position: 'BB',
    stack: 9900,
    stack_bb: 99,
    street_bet: 100,
    total_contribution: 100,
    last_action: 'grosse blinde',
    status: 'active',
    is_dealer: false,
    is_small_blind: false,
    is_big_blind: true,
    profile: {
      initial: 'unknown',
      estimated: 'Inconnu',
      confidence: 0.05,
      hands_observed: 0,
      adaptation_enabled: true,
    },
  },
];

export const advice: Advice = {
  id: 'advice-1',
  hand_id: 'hand-1',
  street: 'preflop',
  balanced: {
    headline: 'Relance standard',
    action: 'raise',
    amount: 250,
    confidence: 0.78,
    source: 'precomputed',
    is_exact: false,
    explanation: 'La position et la profondeur favorisent une relance.',
    options: [
      { action: 'raise', label: 'Raise', amount: 250, frequency: 0.8, ev: 2.4 },
      { action: 'call', label: 'Call', frequency: 0.2, ev: 1.1 },
    ],
  },
  exploitative: {
    headline: 'Relance de valorisation',
    action: 'raise',
    amount: 300,
    confidence: 0.62,
    source: 'model',
    is_exact: false,
    explanation: 'L’échantillon adverse reste limité.',
    options: [{ action: 'raise', label: 'Raise', amount: 300, frequency: 1, ev: 2.7 }],
  },
  final: {
    headline: 'Relancer prudemment',
    action: 'raise',
    amount: 250,
    confidence: 0.71,
    source: 'simulation',
    is_exact: false,
    explanation: 'Le garde-fou réduit l’adaptation.',
    options: [
      { action: 'raise', label: 'Raise', amount: 250, frequency: 0.75, ev: 2.3 },
      { action: 'call', label: 'Call', frequency: 0.25, ev: 1.2 },
    ],
  },
  robust_action: { action: 'raise', label: 'Raise à 250', amount: 250, frequency: 0.75, ev: 2.3 },
  pot_odds: 0.25,
  minimum_equity: 0.25,
  estimated_equity: 0.54,
  spr: 9.2,
  effective_stack: 9900,
  limitations: ['Ranges adverses estimées', 'Abstraction locale'],
  explanation_pending: false,
};

export function tableState(overrides: Partial<TableState['hand']> = {}): TableState {
  return {
    session_id: 'session-1',
    hand: {
      id: 'hand-1',
      number: 1,
      street: 'preflop',
      phase: 'playing',
      unit: 'chips',
      small_blind: 50,
      big_blind: 100,
      ante: 0,
      pot: 150,
      side_pots: [],
      to_call: 0,
      current_bet: 100,
      last_full_raise: 100,
      active_player_id: 'hero',
      players_remaining: 2,
      board: [],
      hero_cards: [],
      action_log: [],
      ...overrides,
    },
    players,
    legal_actions: [
      { action: 'fold', enabled: true },
      { action: 'check', enabled: true },
      { action: 'call', enabled: false, reason: 'Rien à suivre' },
      { action: 'bet', enabled: true, min_amount: 100, max_amount: 9900 },
      { action: 'raise', enabled: false, reason: 'Aucune mise adverse' },
    ],
    selector: { next_slot: 'hero_1', required_slots: ['hero_1', 'hero_2'] },
    advice,
    persistence_status: 'saved',
  };
}
